source "https://rubygems.org"

gem "nokogiri"
gem "fastlane", '~> 2.226.0'
gem "dotenv"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
