name: Alpha Deploy (AppDistribution)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-15

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: "recursive"
          fetch-depth: "0"

      - name: Set active Xcode path
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Create canonical source directory
        run: |
          set -x
          sudo mkdir -p /Users/Shared
          cp -R $GITHUB_WORKSPACE /Users/Shared/
          mv /Users/Shared/$(basename $GITHUB_WORKSPACE) /Users/Shared/telegram-ios

      - name: Restore Bazel cache
        id: restore-bazel-cache
        uses: actions/cache/restore@v4
        with:
          path: "/Users/Shared/telegram-bazel-cache"
          key: bazel-adhoc

      - name: New app distribution build
        run: |
          set -x

          mkdir -p $BUILD_WORKING_DIR
          cd $SOURCE_PATH/ci
          fastlane deploy_ad

      - name: Save Bazel cache
        id: save-bazel-cache
        uses: actions/cache/save@v4
        with:
          path: "/Users/Shared/telegram-bazel-cache"
          key: bazel-adhoc

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Artifacts
      #     path: /Users/Shared/build-working-dir/artifacts

    env:
      CI: 1
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APP_STORE_CONNECT_API_PRIVATE_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY_CONTENT }}
      BAZEL_USER_ROOT: /private/var/tmp/_bazel_telegram
      BAZEL_LOCAL_CACHE: /Users/Shared/telegram-bazel-cache
      BUILD_WORKING_DIR: /Users/Shared/build-working-dir
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      CERTS_GIT_URL: ${{ secrets.CERTS_GIT_URL }}
      SOURCE_PATH: /Users/Shared/telegram-ios
      TELEGRAM_CODESIGNING_GIT_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      TELEGRAM_CODESIGNING_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
