name: Stable branch

on:
  push:
    branches:
      - main
      - master
      - dev

  pull_request:
    branches:
      - main
      - master
      - dev

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  stable-branch:
    runs-on: macos-15

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: "recursive"
          fetch-depth: "0"

      - name: Set active Xcode path
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Create canonical source directory
        run: |
          set -x
          sudo mkdir -p /Users/Shared
          cp -R $GITHUB_WORKSPACE /Users/Shared/
          mv /Users/Shared/$(basename $GITHUB_WORKSPACE) /Users/Shared/telegram-ios

      - name: Build project
        run: |
          set -x

          mkdir -p $BUILD_WORKING_DIR
          cd $SOURCE_PATH/ci
          fastlane build

    env:
      CI: 1
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APP_STORE_CONNECT_API_PRIVATE_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY_CONTENT }}
      BAZEL_USER_ROOT: /private/var/tmp/_bazel_telegram
      BUILD_WORKING_DIR: /Users/Shared/build-working-dir
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      CERTS_GIT_URL: ${{ secrets.CERTS_GIT_URL }}
      SOURCE_PATH: /Users/Shared/telegram-ios
      TELEGRAM_CODESIGNING_GIT_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      TELEGRAM_CODESIGNING_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
